"""Analyst buy/hold/sell consensus + a readable explanation of the cases.

Distribution and price targets come from Yahoo (via yfinance). The plain-English
bull / hold / bear write-up is generated by Claude when an API key is set, and
falls back to a templated summary otherwise. Only equities have analyst
coverage, so indices/commodities/FX return {available: False}.
"""

from __future__ import annotations

import json
import time

import yfinance as yf

from ..config import settings
from . import market

_cache: dict[str, tuple[float, dict]] = {}
_TTL = 3600


def _distribution(t: yf.Ticker) -> dict | None:
    try:
        rec = t.recommendations
    except Exception:
        return None
    if rec is None or len(rec) == 0:
        return None
    try:
        if "period" in rec.columns:
            match = rec[rec["period"] == "0m"]
            row = match.iloc[0] if len(match) else rec.iloc[0]
        else:
            row = rec.iloc[0]
    except Exception:
        row = rec.iloc[0]

    def g(k: str) -> int:
        try:
            return int(row.get(k, 0) or 0)
        except Exception:
            return 0

    sb, b, h, s, ss = g("strongBuy"), g("buy"), g("hold"), g("sell"), g("strongSell")
    total = sb + b + h + s + ss
    if total == 0:
        return None
    buy, sell = sb + b, s + ss
    return {
        "total": total,
        "counts": {"strong_buy": sb, "buy": b, "hold": h, "sell": s, "strong_sell": ss},
        "buy": buy,
        "hold": h,
        "sell": sell,
        "buy_pct": buy / total * 100,
        "hold_pct": h / total * 100,
        "sell_pct": sell / total * 100,
    }


def consensus(symbol: str) -> dict:
    hit = _cache.get(symbol)
    if hit:
        # Cache real results for an hour, but recheck "unavailable" every few
        # minutes so a transient yfinance hiccup doesn't hide it for an hour.
        ttl = _TTL if hit[1].get("available") else 180
        if time.time() - hit[0] < ttl:
            return hit[1]

    t = yf.Ticker(symbol)
    dist = _distribution(t)
    if dist is None:
        result = {"symbol": symbol, "available": False}
        _cache[symbol] = (time.time(), result)
        return result

    try:
        info = t.info
    except Exception:
        info = {}

    def num(*keys) -> float | None:
        for k in keys:
            v = info.get(k)
            if v is not None:
                try:
                    return float(v)
                except (TypeError, ValueError):
                    continue
        return None

    targets = {
        "mean": num("targetMeanPrice"),
        "high": num("targetHighPrice"),
        "low": num("targetLowPrice"),
        "median": num("targetMedianPrice"),
    }
    current = num("currentPrice", "regularMarketPrice")
    upside = None
    if targets["mean"] and current:
        upside = (targets["mean"] - current) / current * 100

    result = {
        "symbol": symbol,
        "name": market.resolve_name(symbol),
        "available": True,
        "key": info.get("recommendationKey"),
        "mean": num("recommendationMean"),
        "analysts": int(info.get("numberOfAnalystOpinions") or dist["total"]),
        "distribution": dist,
        "targets": targets,
        "current": current,
        "upside_pct": upside,
    }
    result.update(_narrative(result, info))
    _cache[symbol] = (time.time(), result)
    return result


def _fallback(r: dict) -> dict:
    d = r["distribution"]
    key = (r.get("key") or "mixed").replace("_", " ")
    summary = (
        f"{r['name']} has a {key} consensus from {r['analysts']} analysts: "
        f"{d['buy_pct']:.0f}% rate it Buy, {d['hold_pct']:.0f}% Hold, and "
        f"{d['sell_pct']:.0f}% Sell."
    )
    if r.get("upside_pct") is not None and r["targets"]["mean"]:
        summary += (
            f" The average 12-month price target is "
            f"{r['targets']['mean']:.2f} ({r['upside_pct']:+.0f}% vs the current price)."
        )
    return {
        "summary": summary,
        "bull": "Bulls point to the upside toward analysts' average price target and the company's growth prospects.",
        "hold": "Those on the sidelines think the stock is roughly fairly valued here and want to see more before adding.",
        "bear": "Bears worry about valuation and the risks to future growth at the current price.",
        "ai": False,
    }


def _narrative(r: dict, info: dict) -> dict:
    if not settings.anthropic_api_key:
        return _fallback(r)
    try:
        import anthropic

        d = r["distribution"]
        tg = r["targets"]
        pe = info.get("trailingPE")
        fpe = info.get("forwardPE")
        margin = info.get("profitMargins")
        stats = []
        if pe:
            stats.append(f"trailing P/E {pe:.1f}")
        if fpe:
            stats.append(f"forward P/E {fpe:.1f}")
        if margin is not None:
            stats.append(f"profit margin {margin * 100:.0f}%")
        stats_txt = ", ".join(stats) if stats else "n/a"
        target_txt = (
            f"avg {tg['mean']:.2f} (range {tg['low']:.0f}–{tg['high']:.0f}); "
            f"{r['upside_pct']:+.0f}% vs current {r['current']:.2f}"
            if tg["mean"] and r.get("current")
            else "n/a"
        )

        prompt = (
            "You are explaining Wall Street analyst sentiment to a smart beginner. "
            "Use plain English; briefly explain any jargon.\n\n"
            f"Asset: {r['name']} ({r['symbol']})\n"
            f"Analyst consensus ({r['analysts']} analysts): "
            f"{d['buy_pct']:.0f}% Buy, {d['hold_pct']:.0f}% Hold, {d['sell_pct']:.0f}% Sell. "
            f"Overall rating: {r.get('key') or 'n/a'}.\n"
            f"12-month price target: {target_txt}.\n"
            f"Key stats: {stats_txt}.\n\n"
            "Respond with ONLY a JSON object with these four fields, each easy to "
            "understand for a non-expert:\n"
            '  "summary": 2-3 sentences on the overall view and what the consensus means.\n'
            '  "bull": why some analysts say Buy (the bull case).\n'
            '  "hold": why some say Hold / stay neutral.\n'
            '  "bear": why some say Sell (the bear case and key risks).\n'
            "Be specific and grounded in the numbers above. JSON only, no markdown."
        )
        client = anthropic.Anthropic(api_key=settings.anthropic_api_key)
        msg = client.messages.create(
            model=settings.narrative_model,
            max_tokens=800,
            messages=[{"role": "user", "content": prompt}],
        )
        text = "".join(
            getattr(b, "text", "") for b in msg.content if getattr(b, "type", "") == "text"
        ).strip()
        # Be tolerant of stray markdown fences.
        if text.startswith("```"):
            text = text.strip("`")
            text = text[text.find("{") :]
        data = json.loads(text[text.find("{") : text.rfind("}") + 1])
        return {
            "summary": data.get("summary", ""),
            "bull": data.get("bull", ""),
            "hold": data.get("hold", ""),
            "bear": data.get("bear", ""),
            "ai": True,
        }
    except Exception:
        return _fallback(r)
